import { ClientItem } from "@/lib/types/dashboardpsikolog";

export const clientListData: ClientItem[] = [
  {
    id: "1",
    name: "Anton",
    role: "Pekerja 23 Tahun",
    image: "/images/clients/anton.jpg",
    priority: "Prioritas Tinggi",
    mood: "Rendah",
    trend: "Menurun",
    screeningResults: [
      { label: "Kecemasan (GAD-7)", value: "Rendah", level: "Rendah" },
      { label: "Stres (PSS)", value: "Sedang", level: "Sedang" },
    ],
    aiSummary: [
      "Stres ringan akibat pekerjaan dan tekanan hidup",
      "Kurang tidur karena stres",
      "Kurang makan karena stres",
    ],
  },
  {
    id: "2",
    name: "Fiky",
    role: "Wibu 40 Tahun",
    image: "/images/clients/fiky.jpg",
    priority: "Prioritas Rendah",
    mood: "Sedang",
    trend: "Stabil",
    screeningResults: [
      { label: "Kecemasan (GAD-7)", value: "Sedang", level: "Sedang" },
      { label: "Stres (PSS)", value: "Rendah", level: "Rendah" },
    ],
    aiSummary: [
      "Kondisi emosional relatif stabil minggu ini",
      "Tidak ada keluhan tidur yang signifikan",
      "Pola makan dalam batas normal",
    ],
  },
  {
    id: "3",
    name: "Amba",
    role: "Pekerja 55 Tahun",
    image: "/images/clients/amba.jpg",
    priority: "Prioritas Rendah",
    mood: "Sedang",
    trend: "Tinggi",
    screeningResults: [
      { label: "Kecemasan (GAD-7)", value: "Sedang", level: "Sedang" },
      { label: "Stres (PSS)", value: "Tinggi", level: "Tinggi" },
    ],
    aiSummary: [
      "Tingkat stres meningkat dalam dua minggu terakhir",
      "Sering mengeluh kelelahan di siang hari",
      "Disarankan evaluasi beban kerja",
    ],
  },
  {
    id: "4",
    name: "Anton",
    role: "Pekerja 28 Tahun",
    image: "/images/clients/anton.jpg",
    priority: "Prioritas Tinggi",
    mood: "Rendah",
    trend: "Menurun",
    screeningResults: [
      { label: "Kecemasan (GAD-7)", value: "Rendah", level: "Rendah" },
      { label: "Stres (PSS)", value: "Sedang", level: "Sedang" },
    ],
    aiSummary: [
      "Stres ringan akibat pekerjaan dan tekanan hidup",
      "Kurang tidur karena stres",
      "Kurang makan karena stres",
    ],
  },
  {
    id: "5",
    name: "Fiky",
    role: "Wibu 40 Tahun",
    image: "/images/clients/fiky.jpg",
    priority: "Prioritas Rendah",
    mood: "Sedang",
    trend: "Stabil",
    screeningResults: [
      { label: "Kecemasan (GAD-7)", value: "Sedang", level: "Sedang" },
      { label: "Stres (PSS)", value: "Rendah", level: "Rendah" },
    ],
    aiSummary: [
      "Kondisi emosional relatif stabil minggu ini",
      "Tidak ada keluhan tidur yang signifikan",
      "Pola makan dalam batas normal",
    ],
  },
  {
    id: "6",
    name: "Amba",
    role: "Pekerja 55 Tahun",
    image: "/images/clients/amba.jpg",
    priority: "Prioritas Rendah",
    mood: "Sedang",
    trend: "Tinggi",
    screeningResults: [
      { label: "Kecemasan (GAD-7)", value: "Sedang", level: "Sedang" },
      { label: "Stres (PSS)", value: "Tinggi", level: "Tinggi" },
    ],
    aiSummary: [
      "Tingkat stres meningkat dalam dua minggu terakhir",
      "Sering mengeluh kelelahan di siang hari",
      "Disarankan evaluasi beban kerja",
    ],
  },
  {
    id: "7",
    name: "Anton",
    role: "Pekerja 28 Tahun",
    image: "/images/clients/anton.jpg",
    priority: "Prioritas Tinggi",
    mood: "Rendah",
    trend: "Menurun",
    screeningResults: [
      { label: "Kecemasan (GAD-7)", value: "Rendah", level: "Rendah" },
      { label: "Stres (PSS)", value: "Sedang", level: "Sedang" },
    ],
    aiSummary: [
      "Stres ringan akibat pekerjaan dan tekanan hidup",
      "Kurang tidur karena stres",
      "Kurang makan karena stres",
    ],
  },
  {
    id: "8",
    name: "Fiky",
    role: "Wibu 40 Tahun",
    image: "/images/clients/fiky.jpg",
    priority: "Prioritas Rendah",
    mood: "Sedang",
    trend: "Stabil",
    screeningResults: [
      { label: "Kecemasan (GAD-7)", value: "Sedang", level: "Sedang" },
      { label: "Stres (PSS)", value: "Rendah", level: "Rendah" },
    ],
    aiSummary: [
      "Kondisi emosional relatif stabil minggu ini",
      "Tidak ada keluhan tidur yang signifikan",
      "Pola makan dalam batas normal",
    ],
  },
  {
    id: "9",
    name: "Amba",
    role: "Pekerja 55 Tahun",
    image: "/images/clients/amba.jpg",
    priority: "Prioritas Rendah",
    mood: "Sedang",
    trend: "Tinggi",
    screeningResults: [
      { label: "Kecemasan (GAD-7)", value: "Sedang", level: "Sedang" },
      { label: "Stres (PSS)", value: "Tinggi", level: "Tinggi" },
    ],
    aiSummary: [
      "Tingkat stres meningkat dalam dua minggu terakhir",
      "Sering mengeluh kelelahan di siang hari",
      "Disarankan evaluasi beban kerja",
    ],
  },
];